### ISSUE TITLE
Brute force version

### ISSUE THREAD

**Issue by fjania** [jreneew2/loopChallenge#2]
For the brute force version in https://github.com/jreneew2/loopChallenge/blob/2c085b2065b234bbebe44b7d85bc0e1c9a0ee20a/loop_challenge.py

If n is the number of entries in the dictionary
What's the O() running time?
What's the O() space used?

**Comment by jreneew2** [comment]
Here is my train of thought:

for the solve function:
- for loop over num of rotations -> O(1) because constant amount of work
- for loop over chars in current word -> O(m) where m is number of letters in word. We count this because it scaled with the length of the word
- checking if the new word is in the dict -> O(n) where n is number of words in dictonary. (This could be O(nlogn) if we used binary search because the data is sorted). Im pretty sure the code I wrote is just linear searching though.
So for the solve function overall its O(n+m).

for solve_all:
We would just multiply solve function runtime by n again because we iterate through all entries in the word list. 

So the total runtime is O(n^2 + nm)

**Comment by jreneew2** [comment]
For space, 

we are holding all of the words in memory when we initialize the list. So we are using O(n) memory. 

I think thats all we are doing with memory but I'm less confident on this one

**Comment by fjania** [comment]
I think it's fair to say O(n) space. It certainly O(n*`avg word length`).

For computational complexity I'd say count the number of rotations for now. Big O is helpful for gross measures - getting a O(n^2) down to O(n*log n), but there's something to be said for getting a computation down from 25n to 10n or whatever.

The very first brute force I tired was O(n^2). It was super slow. I wrote the function to test if two words were rotations, and then tested every word pair. That's exhaustive, but inefficient. It was super slow. I did some short-circuiting to make it faster, but it was still slow.

You've stared better than that, either by recognizing that n*n  is much larger than 25*n, or just intuiting that generating the possible rotations of a word would fewer computations.

Also, I don't know if it was intentional or not, but you built deduplication in too - you only search for `ord + 25`. So you'd find beef -> loop, but you wouldn't find loop -> beef. Why? (Does this represent wasted work?)

**Comment by jreneew2** [comment]
I agree with counting the rotations as well, I didn't include it originally because it sort of breaks what big O means but I still think it matters for practical performance.

Honestly, the first thing that popped into my head was generating the new words. Maybe because I knew checking the list twice would be worse. 

I didn't check the reverse because if I'm checking against the same dictionary as I am pulling from, it will show up as an original word eventually. The only thing I miss is doing -25 rotations. I think that matters because you won't get the original word in the list but only as a result of another rotation if you get what I am saying.

**Comment by fjania** [comment]
If the was `zulus` what would all the 25 possible rotations be that you're checking?

**Comment by jreneew2** [comment]
whatever is past the ascii table from z, so a bunch of non-letter characters.

**Comment by fjania** [comment]
Yeap. But just leave that aside for now... I believe the more optimal solution won't encounter this problem.
